Add HTTPS redirect package
yourbase/commons pull request #2
Opened 2020-08-04 16:52 UTC by zombiezen

2020-08-04 20:35 UTC, glacials requested changes
Open to argument here, but important enough to block.

2020-08-04 20:35 UTC, glacials commented on https/https.go
> +		http.Redirect(w, r, u.String(), http.StatusPermanentRedirect)
308 Permanent Redirect is touchy when doing specifically HTTP -> HTTPS redirects, because many client libraries (e.g. `net/http`) follow redirects by default without telling the developer. If a developer accidentally builds an integration to use plaintext HTTP, they might never know it if we return a 308, and the whole advantage of forcing HTTPS is lost for that consumer -- all the data they send is exposed on the wire.

If we instead fail loudly by returning 301 Moved Permanently, we can at least limit this behavior to GETs, which generally won't have as much sensitive data in the request.

2020-08-04 21:28 UTC, zombiezen commented on https/https.go
> +		http.Redirect(w, r, u.String(), http.StatusPermanentRedirect)
Nice catch! So maybe we should return [410 Gone](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410) for non-HEAD/non-GET requests to make this fail as loudly as possible?

2020-08-04 21:34 UTC, glacials commented on https/https.go
> +		http.Redirect(w, r, u.String(), http.StatusPermanentRedirect)
Sure, that's fine with me! I'm not too concerned with the specific solution, as long as it's a solution :P

2020-08-05 15:20 UTC, zombiezen commented on https/https.go
> +		http.Redirect(w, r, u.String(), http.StatusPermanentRedirect)
Done.

2020-08-05 16:43 UTC, glacials approved these changes

2020-08-05 16:48 UTC, merged